ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
concurrency: 2
tunnel:
  type: ngrok
  bind_tls: true
